### ISSUE TITLE
not working with vercel deploy?

### ISSUE THREAD

**Issue by ctwhome** [antfu/unplugin-icons#112]
I am using https://github.com/nuxt/vercel-builder
and this is what I get in the logs

![image](https://user-images.githubusercontent.com/4195550/140533696-17a5aa62-8eb1-439b-8891-478ec2623948.png)

```
16:08:24.232	node_modules_dev/unplugin-icons/types/vue3.d.ts(2,12): error TS2614: Module '"vue"' has no exported member 'FunctionalComponent'. Did you mean to use 'import FunctionalComponent from "vue"' instead?
16:08:24.233	node_modules_dev/unplugin-icons/types/vue3.d.ts(2,33): error TS2614: Module '"vue"' has no exported member 'SVGAttributes'. Did you mean to use 'import SVGAttributes from "vue"' instead?
16:08:24.233	node_modules_dev/unplugin-icons/types/vue3.d.ts(7,12): error TS2614: Module '"vue"' has no exported member 'FunctionalComponent'. Did you mean to use 'import FunctionalComponent from "vue"' instead?
16:08:24.233	node_modules_dev/unplugin-icons/types/vue3.d.ts(7,33): error TS2614: Module '"vue"' has no exported member 'SVGAttributes'. Did you mean to use 'import SVGAttributes from "vue"' instead?
16:08:24.254	Error: Command failed with exit code 2: npx tsc --target ES2018 --module ESNext --moduleResolution Node --lib ESNext,ESNext.AsyncIterable,DOM --esModuleInterop true --allowJs true --sourceMap true --strict true --experimentalDecorators true --baseUrl . --types @nuxt/types,@nuxt/content,@types/node,unplugin-icons/types/vue,@nuxtjs/i18n --noEmit false --rootDir /vercel/path1 --outDir now_compiled nuxt.config.ts
16:08:24.254	at makeError (/vercel/bde74988fa2cf27a/.build-utils/.builder/node_modules/execa/lib/error.js:60:11)
16:08:24.254	at handlePromise (/vercel/bde74988fa2cf27a/.build-utils/.builder/node_modules/execa/index.js:118:26)
16:08:24.254	at processTicksAndRejections (internal/process/task_queues.js:95:5)
16:08:24.255	at compileTypescriptBuildFiles (/vercel/bde74988fa2cf27a/.build-utils/.builder/node_modules/@nuxtjs/vercel-builder/lib/index.js:221:3)
16:08:24.255	at Object.build (/vercel/bde74988fa2cf27a/.build-utils/.builder/node_modules/@nuxtjs/vercel-builder/lib/index.js:334:31)
16:08:24.255	at buildStep (/var/task/webpack:/@vercel/api/scripts/build-container/src/utils/purpose-build.ts:184:1) {
```

**Comment by Froskk** [comment]
Also not working with next / vercel
