### ISSUE TITLE
[Bug Report] broken in ESM project - Dynamic require of "@vue/compiler-sfc" is not supported

### ISSUE THREAD

**Issue by josh-hemphill** [antfu/unplugin-icons#120]
In a project with `"type":"module"` set:
```txt
[vite-plugin-pwa] Could not load ~icons/carbon/warning (imported by src\layouts\error.vue): Dynamic require of "@vue/compiler-sfc" is not supported      
Error: Could not load ~icons/carbon/warning (imported by src\layouts\error.vue): Dynamic require of "@vue/compiler-sfc" is not supported
    at file:///C:/Users/joshua/test/node_modules/unplugin-icons/dist/chunk-QVRFTMN2.mjs:30:9
    at file:///C:/Users/joshua/test/node_modules/unplugin-icons/dist/chunk-MN45D3WG.mjs:232:77
    at async Vue3Compiler (file:///C:/Users/joshua/test/node_modules/unplugin-icons/dist/chunk-MN45D3WG.mjs:232:31
```

```js
/* unplugin-icons/dist/chunk-MN45D3WG.mjs:232:77 */
// src/core/compilers/vue3.ts
var Vue3Compiler = async (svg, collection, icon) => {
  const { compileTemplate } = await Promise.resolve().then(() => __toModule(__require("@vue/compiler-sfc")));
  const { injectScripts, svg: handled } = handleSVGId(svg);
  let { code } = compileTemplate({
    source: handled,
    id: `${collection}:${icon}`,
    filename: `${collection}-${icon}.vue`
  });
```

**Comment by userquin** [comment]
@josh-hemphill can you provide a repro?

**Comment by josh-hemphill** [comment]
It should be re-creatable with the default vitesse vue-3 starter template by just setting the type.

**Comment by userquin** [comment]
@josh-hemphill error recreated in this repo on vue3 example and fixed, creating PR...

**Comment by josh-hemphill** [comment]
Awesome, thanks!
