### ISSUE TITLE
Failed to resolve import for various icons like "~icons/ph/cursor-fill"

### ISSUE THREAD

**Issue by jojobyte** [antfu/unplugin-icons#123]
slidev server (`npm run dev` in a slidev project) just started spitting this out, found that setting `"unplugin-icons": "0.12.18",` to that fixes the problem, so looks like theres an issue with `0.12.19`

```bash
[vite] Internal server error: Failed to resolve import "~icons/ph/cursor-fill" from "node_modules/@slidev/client/internals/PresenterMouse.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: ~/slides/node_modules/@slidev/client/internals/PresenterMouse.vue
  1  |  /* unplugin-vue-components disabled */import __unplugin_components_0 from '~icons/ph/cursor-fill';
     |                                                                             ^
  2  |  import { defineComponent as _defineComponent } from "vue";
  3  |  import { serverState } from "../env";
      at formatError (~/slides/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42189:46)
      at TransformContext.error (~/slides/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42185:19)
      at normalizeUrl (~/slides/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:67284:26)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (~/slides/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:67424:57)
      at async Object.transform (~/slides/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42396:30)
      at async doTransform (~/slides/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:56801:29)

```

**Comment by galvez** [comment]
Reverting to previous release did the trick for me.
