### ISSUE TITLE
Can't find icons after vite start with .vue ending

### ISSUE THREAD

**Issue by anbraten** [antfu/unplugin-icons#38]
I tried to import my icons via the following two ways:
```ts
import IconStatusBlocked from '/@vite-icons/ph/hand.vue';
```
and

```ts
import IconStatusBlocked from 'virtual:vite-icons/ph/hand.vue';
```

To get TS support I added `.vue` to my imports which worked fine while the vite-server was running, but after a restart of vite I get this error:

```
 > html:/home/***.vue:3:30: error: Do not know how to load path: html:@vite-icons/ph/hand
    3 │ import IconStatusBlocked from 'virtual:vite-icons/ph/hand.vue';
      ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > html:/home/***.vue:8:30: error: Do not know how to load path: html:@vite-icons/ph/hourglass
    8 │ import IconStatusPending from 'virtual:vite-icons/ph/hourglass.vue';
      ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 16 errors:
html:/home/***.vue:3:25: error: Do not know how to load path: html:@vite-icons/ic/sharp-timelapse
html:/home/***.vue:4:22: error: Do not know how to load path: html:@vite-icons/mdi/clock-time-eight-outline
html:/home/***.vue:5:23: error: Do not know how to load path: html:@vite-icons/mdi/source-branch
html:/home/***.vue:6:23: error: Do not know how to load path: html:@vite-icons/mdi/source-commit
html:/home/***.vue:3:30: error: Do not know how to load path: html:@vite-icons/ph/hand
...
    at failureErrorWithLog (/home/***/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:1449:15)
    at /home/***/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/home/***/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/home/***/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:1129:7)
    at /home/***/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:1236:14
    at /home/***/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/home/***/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/home/***/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
 ERROR  Command failed with exit code 1.
```

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by anbraten** [comment]
https://github.com/anbraten/repro-vite-icons

What I did:

```
pnpm i
pnpm start
```

The error:
```
> repro-vite-icons@1.0.0 start /home/***/repro-vite-icons
> vite

 > html:/home/***/repro-vite-icons/src/App.vue:3:20: error: Do not know how to load path: html:@vite-icons/ph/check-circle
    3 │ import IconOne from 'virtual:vite-icons/ph/check-circle.vue';
      ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 1 error:
html:/home/***/repro-vite-icons/src/App.vue:3:20: error: Do not know how to load path: html:@vite-icons/ph/check-circle
    at failureErrorWithLog (/home/***/repro-vite-icons/node_modules/.pnpm/esbuild@0.12.17/node_modules/esbuild/lib/main.js:1449:15)
    at /home/***/repro-vite-icons/node_modules/.pnpm/esbuild@0.12.17/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/home/***/repro-vite-icons/node_modules/.pnpm/esbuild@0.12.17/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/home/***/repro-vite-icons/node_modules/.pnpm/esbuild@0.12.17/node_modules/esbuild/lib/main.js:1129:7)
    at /***/Projects/repro-vite-icons/node_modules/.pnpm/esbuild@0.12.17/node_modules/esbuild/lib/main.js:1236:14
    at /***/Projects/repro-vite-icons/node_modules/.pnpm/esbuild@0.12.17/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/home/***/repro-vite-icons/node_modules/.pnpm/esbuild@0.12.17/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/home/***/repro-vite-icons/node_modules/.pnpm/esbuild@0.12.17/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
 ERROR  Command failed with exit code 1.
```

It can start the server if I remove `.vue` at before starting the server and re-add it after the server is running. Seems like some path-resolution is cached after starting.

**Comment by anbraten** [comment]
@antfu I changed the reproduction to use npm and latest stable vue3, but still no success.

**Comment by antfu** [comment]
@anbraten Can you try with the latest `unplugin-icons`?

**Comment by antfu** [comment]
Close for now. Feel free to reopen if it still persists.
