### ISSUE TITLE
Error loading custom Icons

### ISSUE THREAD

**Issue by kmilogp8496** [antfu/unplugin-icons#61]
Hi, I'm having this error when trying to reproduce vite + vue3 example

```
[vite] Internal server error: Cannot read property 'icons' of null
      at Collection.getIconData (C:\Users\kmilo\Desktop\Devitall\dentos\frontend\node_modules\.pnpm\@iconify+json-tools@1.0.10\node_modules\@iconify\json-tools\src\collection.js:461:18)
      at getBuiltinIcon (C:\Users\kmilo\Desktop\Devitall\dentos\frontend\node_modules\.pnpm\unplugin-icons@0.11.2_954f950b29577c0f46930e88ab1c74d1\node_modules\unplugin-icons\dist\chunk-3NPAQMBG.js:162:18)
      at getIcon (C:\Users\kmilo\Desktop\Devitall\dentos\frontend\node_modules\.pnpm\unplugin-icons@0.11.2_954f950b29577c0f46930e88ab1c74d1\node_modules\unplugin-icons\dist\chunk-3NPAQMBG.js:185:20)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async generateComponent (C:\Users\kmilo\Desktop\Devitall\dentos\frontend\node_modules\.pnpm\unplugin-icons@0.11.2_954f950b29577c0f46930e88ab1c74d1\node_modules\unplugin-icons\dist\chunk-3NPAQMBG.js:194:13)
```

OS => Windows 10
dependencies =>
```
"unplugin-auto-import": "^0.2.6",
    "unplugin-icons": "^0.11.2",
    "unplugin-vue-components": "^0.15.1",
    "vite": "^2.5.7",
```
icon folder =>
![image](https://user-images.githubusercontent.com/52615668/133474580-1157adcb-7168-41db-9405-42e5a010e246.png)
vite.config =>
```
Components({
      directoryAsNamespace: true,
      dirs: ['src/components/FormInput', 'src/components/Common', 'src/components'],

      extensions: ['vue'],

      dts: true,

      include: [/\.vue$/, /\.vue\?vue/],

      resolvers: [
        IconsResolver({
          componentPrefix: '',
          customCollections: ['custom'],
        }),
      ],
      exclude: ['src/pages'],
    }),

    Icons({
      compiler: 'vue3',
      customCollections: {
        custom: FileSystemIconLoader('assets/custom-a'),
      },
    }),
```
import in component =>
```
<custom-menu-arrow />
```

Please, some help if I'm doing something wrong, I really like this tool
Thanks

**Comment by kmilogp8496** [comment]
It was an error in configuration with the icon source directory
