### ISSUE TITLE
[vite-react] Runtime error in vite-react example

### ISSUE THREAD

**Issue by IanVS** [antfu/unplugin-icons#66]
I'm trying to run the vite-react example from the examples folder, but am getting a runtime error.  Here's what I did:

```
cd unplugin-icons
pnpm install
pnpm run build
cd examples/vite-react
pnpm run dev
```

The build completes, but when I open the browser I get this error in the console:

```
Uncaught ReferenceError: React is not defined
    at logosReact (react.jsx:2)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)

The above error occurred in the <logosReact> component:

    at logosReact (http://localhost:3000/@id/~icons/logos/react.jsx:2:3)
    at header
    at div
    at App (http://localhost:3000/src/App.tsx:31:29)

```

**Comment by IanVS** [comment]
Adding `jsx: 'react',` to the options fixes this issue.  I'll submit a PR for it.
